version: '3.7'

services:
  db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "user_db"]
      interval: 2s
      timeout: 2s
      retries: 10

  user_service:
    build: ./user_service
    container_name: user_service
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: user_db
      DB_PORT: 5432
      SECRET_KEY: "MY_SUPER_SECRET_KEY"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

  api_service:
    build: ./api_service
    container_name: api_service
    environment:
      USER_SERVICE_URL: "http://user_service:8001"
    depends_on:
      - user_service
    ports:
      - "8000:8000"